development:
  bucket: supportstack_dev
  access_key_id: *************************
  secret_access_key: *************************

production:
  bucket:supportstack_pro
  access_key_id: *************************
  secret_access_key: *************************
